### ISSUE TITLE
required key not provided @ data['topic']

### ISSUE THREAD

**Issue by fcoulloudon** [TroyFernandes/hass-mqtt-mediaplayer#2]
I put the files in cofing/custom_components/mqtt-mediaplayer/

And added this to configuration.yaml:

`media_player:`  
  - platform: mqtt-mediaplayer
    name: "Shairport"
    vol_down:
      service: mqtt.publish
      data:
        topic: "shairport-sync/snapcast/remote"
        payload: "volumedown"
    vol_up:
      service: mqtt.publish
      data:
        topic: "shairport-sync/snapcast/remote"
        payload: "volumeup"``

And got these errors:

Invalid config for [media_player.mqtt-mediaplayer]: required key not provided @ data['topic']. Got None. (See /config/configuration.yaml, line 36). Please check the docs at https://github.com/TroyFernandes/hass-mqtt-mediaplayer
10:36:18 – config.py (ERROR)

You are using a custom integration for mqtt-mediaplayer which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
10:36:17 – loader.py (WARNING)

Any idea why? Have you face this problem before?

**Comment by TroyFernandes** [comment]
Hi, 

Thanks for pointing out this issue. I mistakenly made the "topics" key required even though all of the sub keys were optional. 

I made the change to fix this and it should be working correctly now. Pull the update and let me know if you experience any issues.

**Comment by fcoulloudon** [comment]
Works flawlessly! Thank you.
Interested in feature request? Maybe I can open another issue?
I think media_player.select_source function would be great.

That's the only missing feature to have my Marantz amplifier fully operational.
As well as media_player.turn_on and media_player.turn_off

Let me know 👍 
Excellent job by the way, really appreciate!

**Comment by TroyFernandes** [comment]
I want to keep this component strictly for media players which report their data/status, so for that reason I probably won't implement features such as turning on/off, switching source.

Here's a component that might be a better fit for what you're looking for though: 

https://github.com/Sennevds/media_player.template

I believe that this person made their component for controlling their receiver originally, and should include everything you're looking to do with your receiver.

**Comment by fcoulloudon** [comment]
Thanks a lot! Will have a look.
Else will do it myself.

Have a nice day.

Le lun. 5 oct. 2020 à 22:19, Troy Fernandes <notifications@github.com> a
écrit :
